import Head from "next/head";
import Link from "next/link";
import Style from "@/styles/pages/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Games</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={Style.container}>
        <h1 className={Style.title}>Sélectionner un jeu : </h1>
        <div className={Style.cardsContainer}>
          <Link href="/snake" className={Style.card}>
            Snake
          </Link>
        </div>
      </div>
    </>
  );
}
